# Generated by Django 2.2.16 on 2020-10-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
